import Foundation
import CoreData

@objc(CalendarSettings)
public class CalendarSettings: NSManagedObject {
    
    // Properties that should be generated by Core Data
    @NSManaged public var notificationMinutesBefore: Int16
    @NSManaged public var highlightTitle: String?
    @NSManaged public var highlightStart: Date?
    @NSManaged public var highlightEnd: Date?
    @NSManaged public var highlightDateKey: String?
    
    @nonobjc public class func fetchRequest() -> NSFetchRequest<CalendarSettings> {
        return NSFetchRequest<CalendarSettings>(entityName: "CalendarSettings")
    }
}
