import Foundation
import CoreData

@objc(CalendarTask)
public class CalendarTask: NSManagedObject {
    
    // Properties that should be generated by Core Data
    @NSManaged public var id: UUID?
    @NSManaged public var dateKey: String?
    @NSManaged public var hour: Int16
    @NSManaged public var title: String?
    @NSManaged public var descriptionText: String?
    @NSManaged public var startTime: Date?
    @NSManaged public var endTime: Date?
    @NSManaged public var eventIdentifier: String?
    @NSManaged public var startLocation: String?
    @NSManaged public var destination: String?
    @NSManaged public var assigneesJSON: String?
    
    @nonobjc public class func fetchRequest() -> NSFetchRequest<CalendarTask> {
        return NSFetchRequest<CalendarTask>(entityName: "CalendarTask")
    }
}
