import Foundation
import CoreData

@objc(CompletedTask)
public class CompletedTask: NSManagedObject {
    
    // Properties that should be generated by Core Data
    @NSManaged public var id: UUID?
    @NSManaged public var title: String?
    @NSManaged public var completedAt: Date?
    
    @nonobjc public class func fetchRequest() -> NSFetchRequest<CompletedTask> {
        return NSFetchRequest<CompletedTask>(entityName: "CompletedTask")
    }
}
