import Foundation
import CoreData

@objc(EventMapping)
public class EventMapping: NSManagedObject {
    
    // Properties that should be generated by Core Data
    @NSManaged public var key: String?
    @NSManaged public var eventIdentifier: String?
    
    @nonobjc public class func fetchRequest() -> NSFetchRequest<EventMapping> {
        return NSFetchRequest<EventMapping>(entityName: "EventMapping")
    }
}
